### ISSUE TITLE
Add DRPM fixtures

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-fixtures#11]
Pulp Smash makes use of DRPM files in its tests. See [`pulp_smash.constants.DRPM_FEED_URL`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.constants.html#pulp_smash.constants.DRPM_FEED_URL). Pulp Fixtures should generate DRPM files. This will allow Pulp Smash to rely on this repository instead of the currently referenced files.

**Comment by Ichimonji10** [comment]
We may not want to copy the currently-referenced DRPM files. I'm unfamiliar with how DRPM files are structured, but what's listed there seems slightly messy.

**Comment by jeremycline** [comment]
``createrepo_c`` (when compiled with drpm support) can make you DRPMs and the metadata that describes them (prestodelta.xml)

**Comment by elyezer** [comment]
I tried to create drpms for the zoo repo and it does not generate any, not sure what are the prerequisites in order to generate the DRPMs.

My try was to add `--deltas` option to the createrepo call on the `rpm/gen-fixtures.sh` script.

**Comment by jeremycline** [comment]
Ah, yes. You need to have several versions of the same RPM in a repository. So, for example, if you had firefox-47.0.0-1.fc24.x86_64, firefox-47.0.1-1.fc24.x86_64, firefox-48.0.0-1.fc24.x86_64, and firefox-48.0.3-1.fc24.x86_64 I believe you would get a DRPM for each old version to the latest version (48.0.3)

**Comment by Ichimonji10** [comment]
We have two versions of walrus. That could be a good thing to use.

**Comment by elyezer** [comment]
I tried getting that for Walrus, but it was not possible, maybe the RPM is too simple. More research on this is needed.

**Comment by Ichimonji10** [comment]
Fixed by #17.
