### ISSUE TITLE
Add OSTree fixtures

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-fixtures#30]
Let's add OSTree fixtures. Pulp Smash's [`pulp_smash.tests.ostree`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.ostree.html) tests should use these new fixtures instead of what's currently used.

**Comment by Ichimonji10** [comment]
I'm unclear on whether or not OSTree fixtures can effectively be served via a static webserver, so I'm marking this issue as a "discussion." When the viability of this issue is resolved, it should be changed to a plan, or a new issue should be filed with necessary steps.

**Comment by Ichimonji10** [comment]
Let's just include this tree in Pulp Fixtures. Dumb but easy solution.

**Comment by jortel** [comment]
I will submit a PR with a script to generate the small[1] tree today.

[1] https://repos.fedorapeople.org/pulp/pulp/fixtures/ostree/small/

**Comment by jortel** [comment]
https://github.com/PulpQE/pulp-fixtures/pull/56
