### ISSUE TITLE
Add Puppet fixtures

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-fixtures#31]
Let's add Puppet fixtures. Pulp Smash's [`pulp_smash.tests.puppet`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.puppet.html) tests should use these new fixtures instead of what's currently used.

**Comment by Ichimonji10** [comment]
I'm unclear on whether or not Puppet fixtures can effectively be served via a static webserver, so I'm marking this issue as a "discussion." When the viability of this issue is resolved, it should be changed to a plan, or a new issue should be filed with necessary steps.

**Comment by elyezer** [comment]
There are some Puppet demo repos here [1]. Maybe we can inspire on them to create fixtures.

It seems that we are able to create Puppet fixtures by downloading some modules from Puppet Forge and then create an specific directory structure.

I am not sure if it is going to work, but maybe someone with more experience on Puppet can help us here.

[1] https://repos.fedorapeople.org/pulp/pulp/demo_repos/
