### ISSUE TITLE
provide RPM with vendor data

### ISSUE THREAD

**Issue by kdelee** [PulpQE/pulp-fixtures#54]
[pulp-smash #680](https://github.com/PulpQE/pulp-smash/issues/680) is blocked until an RPM is available that has a "vendor" field that has a value other than "none".

**Comment by Ichimonji10** [comment]
We have several make targets that create custom RPMs, like `fixtures/rpm-with-non-ascii` and `fixtures/rpm-with-non-utf8`. We could create a new one that has a vendor field. This would require we do at least the following:

* Create a new spec file in `rpm/assets-specs/`.
* Create a new make target that calls `rpm/gen-rpm.sh` as appropriate.
