### ISSUE TITLE
Output all fixtures to a single directory

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-fixtures#6]
Let's update the make rules so that each writes to an `output` directory, instead of a top-level directory. This will make `.gitignore` simpler:

    /output/*

This change will also improve the maintainability of all Pulp Fixtures clients, as they will be able to execute `make all` and know that all output will be in a single `output` directory, instead of having to worry about the particulars of what was generated.

**Comment by elyezer** [comment]
:+1:

**Comment by Ichimonji10** [comment]
For context, see [this](https://github.com/pulp/pulp_packaging/blob/master/ci/jobs/pulp-fixtures-publisher.yaml#L24-L26):

```sh
mkdir fixtures
mv docker-fixtures fixtures/docker
mv rpm-fixtures fixtures/rpm
```

**Comment by Ichimonji10** [comment]
I don't know if this is kosher, but it works:

```make
help:
	@echo "Please use \`make <target>' where <target> is one of:"
	@echo "  help            to show this message"
	@echo "  clean           to remove generated artifacts"
	@echo "  all             to make all"
	@echo "  all/foo         to make all/foo"
	@echo "  all/bar         to make all/bar"

clean:
	rm -rf all/*

all: all/foo all/bar

all/foo:
	touch all/foo

all/bar:
	touch all/bar

.PHONY: help clean
```
