### ISSUE TITLE
Fix issues with fixtures/rpm-richnweak-deps* make targets

### ISSUE THREAD

**Issue by Ichimonji10** [PulpQE/pulp-fixtures#91]
The fixtures/rpm-richnweak-deps and fixtures/rpm-richnweak-deps/srpms make targets have some issues that need to be fixed.

First, the README should list every executable that a target requires to run. It doesn't. At the very least, `rpmdev-setuptree` is an undocumented dependency. `createrepo` may be another. It's also notable that the user should belong to the `mock` group in order to build these fixtures without being root.

Second, the `.spec` files used by fixtures/rpm-richnweak-deps/srpms contain invalid changelogs. Warnings like this are raised when fixtures are compiled:

    warning: bogus date in %changelog: Tue Feb 27 2017 Mr. Bartender                                                                                                                                                  

These changelog lines should either be fixed or dropped.

Third, the fixtures/rpm-richnweak-deps repository doesn't include a "repodata" directory. As a result, this repository is not a valid repository.

**Comment by Ichimonji10** [comment]
FYI @dparalen @rochacbruno

**Comment by dparalen** [comment]
@Ichimonji10 thanks for the analysis and tracking!
